In [0]:
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
data = pd.read_excel("Balance_hidrico_ecologico.xlsx")
data

      Lugar  Mes  T_Max  T_min  T_med     Pp  Dias
0   Iquitos    1   31.3   21.7   26.5  258.4    31
1   Iquitos    2   31.4   21.5   26.5  272.4    28
2   Iquitos    3   31.3   21.7   26.3  348.6    31
3   Iquitos    4   30.7   21.6   26.0  291.2    30
4   Iquitos    5   30.6   21.5   26.0  280.2    31
5   Iquitos    6   30.5   20.9   25.7  204.9    30
6   Iquitos    7   30.3   20.3   25.4  164.4    31
7   Iquitos    8   31.7   20.5   26.1  156.1    31
8   Iquitos    9   32.2   21.0   26.7  193.7    30
9   Iquitos   10   32.1   21.6   26.9  228.0    31
10  Iquitos   11   32.0   21.9   26.9  246.0    30
11  Iquitos   12   31.8   21.9   26.9  232.0    31
12  Upamayo    1   12.1    1.3    6.4  105.9    31
13  Upamayo    2   11.7    1.7    6.4  118.5    28
14  Upamayo    3   11.9    1.5    6.3  126.2    31
15  Upamayo    4   12.1   -0.2    6.2   43.7    30
16  Upamayo    5   12.4   -1.2    5.8   28.6    31
17  Upamayo    6   12.6   -0.5    5.0    7.2    30
18  Upamayo    7   12.1   -6.4    4.3   10.4    31
19  Upamayo    8   12.2   -5.1    4.6   25.9    31
20  Upamayo    9   12.2   -3.0    5.0   47.6    30
21  Upamayo   10   12.4   -0.5    5.8   90.6    31
22  Upamayo   11   13.1   -2.2    5.7   87.4    30
23  Upamayo   12   11.8    0.7    5.9  126.8    31
24    Canta    1   17.2    9.3   13.4   72.5    31
25    Canta    2   16.7    9.6   13.2   75.1    28
26    Canta    3   16.4    9.5   13.0   92.8    31
27    Canta    4   17.7    9.4   13.5   33.2    30
28    Canta    5   18.6    9.7   14.1    1.7    31
29    Canta    6   18.3    9.3   13.8    0.0    30
30    Canta    7   18.5    9.5   14.0    0.2    31
31    Canta    8   18.5    9.4   13.9    0.2    31
32    Canta    9   18.6    9.6   14.1    6.9    30
33    Canta   10   18.3    9.4   13.8   16.7    31
34    Canta   11   17.8    9.1   13.5    9.7    30
35    Canta   12   17.4    9.4   13.3   43.8    31
36  Chosica    1   27.4   17.2   22.2    4.6    31
37  Chosica    2   28.2   18.2   23.2    4.6    28
38  Chosica    3   28.6   18.2   23.2    4.9    31
39  Chosica    4   26.6   16.9   21.7    0.9    30
40  Chosica    5   24.0    4.3   19.1    0.1    31
41  Chosica    6   22.0   12.0   17.0    0.0    30
42  Chosica    7   21.5    0.8   16.1    0.0    31
43  Chosica    8   22.9   11.4   17.2    0.0    31
44  Chosica    9   23.8   12.2   18.0    0.0    30
45  Chosica   10   25.0   13.3   19.1    0.5    31
46  Chosica   11   25.6   14.6   20.0    0.4    30
47  Chosica   12   26.4   15.3   20.8    2.0    31

In [0]:
def b(data):
  lista = []
  for i in range(len(data)):
    if data.Dias[i] == 28:
      lista.append(round((58.93 * (4 * data.Dias[i] + 1) * data.T_med[i])/(365 * 4), 1))
    else:
      lista.append(round((58.93 * data.Dias[i] * data.T_med[i])/365, 1))
  data["ETP"] = lista
  data["Balance_Hidrico"] = data.Pp - data.ETP
  lista2 = []
  for i in range(48):
    if data.ETP[i] > data.Pp[i]:
      if data.Balance_Hidrico[i -1] > 0:
        lista2.append(round(data.Pp[i] + data.Balance_Hidrico[i - 1], 1))
      else:
        lista2.append(round(data.Pp[i], 1))
    else:
      lista2.append(round(data.ETP[i], 1))
  lista2
  data["ETR"] = lista2
  return(data)